[project]
name = "todoapp-fullstack"
version = "0.1.0"
description = "Todo App Fullstack"
requires-python = ">=3.11"

dynamic = ["dependencies"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = [
    "main",
    "database",
    "models",
    "config"
]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}